name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: Build
        run: pnpm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.js
